# Generated by Django 4.1.1 on 2022-09-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('insta', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('careerObj', models.CharField(max_length=100)),
                ('we', models.CharField(max_length=100)),
                ('projects', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('aq', models.CharField(max_length=100)),
            ],
        ),
    ]
