# Generated by Django 4.1.1 on 2022-09-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_aq_alter_profile_careerobj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='projects',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='skills',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='we',
            new_name='workexp',
        ),
    ]
